# Generated by Django 4.2.1 on 2023-05-18 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_confirmationcode_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=3, max_digits=100000)),
            ],
        ),
        migrations.AlterField(
            model_name='confirmationcode',
            name='code',
            field=models.CharField(default='1312', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='confirmationcode',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 20, 20, 56, 890808)),
        ),
    ]
