# Generated by Django 4.2.1 on 2023-05-18 01:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_alter_confirmationcode_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='confirmationcode',
            name='code',
            field=models.CharField(default='1806', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='confirmationcode',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 20, 26, 57, 789473)),
        ),
    ]
