# Generated by Django 4.2.1 on 2023-05-19 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_profile_id_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='code',
            field=models.CharField(default='1976', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='confirmationcode',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 10, 1, 32, 641464)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
